"""Generate local Capstone listings for the stock equipment-label functions."""

import argparse
import hashlib
from dataclasses import dataclass
from pathlib import Path

from engine.script.sh2 import disassemble
from project_paths import EXTRACTED_ROOT

SOURCE_ROOT = EXTRACTED_ROOT
OUTPUT_ROOT = Path(__file__).with_name("reference")
LOAD_ADDRESS = 0x06020000


@dataclass(frozen=True)
class ReferenceSpec:
    binary: str
    function: str
    start: int
    end: int

    @property
    def output_path(self) -> Path:
        return OUTPUT_ROOT / f"{self.binary}.{self.function}.original.lst"


SPECS = (
    ReferenceSpec(
        "EVENT.BIN",
        "Shop_DrawEquipActionLabels",
        0x06059716,
        0x06059892,
    ),
    ReferenceSpec(
        "NORMCOM.BIN",
        "Shop_DrawEquipActionLabels",
        0x0603AE2A,
        0x0603AFA6,
    ),
)


def render(spec: ReferenceSpec) -> str:
    source_path = SOURCE_ROOT / spec.binary
    source = source_path.read_bytes()
    start = spec.start - LOAD_ADDRESS
    end = spec.end - LOAD_ADDRESS
    if start < 0 or end <= start or end > len(source):
        raise ValueError(f"{spec.binary}: invalid reference range")
    data = source[start:end]
    lines = (
        "; Generated by equipment_ui/reference.py from the unmodified binary.",
        "; This is a linear Capstone listing; embedded literal data may resemble code.",
        f"; Source: rom/extracted/{spec.binary}",
        f"; Source SHA-256: {hashlib.sha256(source).hexdigest()}",
        f"; Function: {spec.function}",
        f"; Range: {spec.start:#010x}-{spec.end:#010x} ({len(data)} bytes)",
        "",
        *(f"; {line}" for line in disassemble(data, spec.start, require_capstone=True)),
        "",
    )
    return "\n".join(lines)


def update(check: bool) -> None:
    stale = []
    for spec in SPECS:
        expected = render(spec)
        path = spec.output_path
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path)
                action = "stale"
            else:
                action = "verified"
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
            action = "wrote"
        print(f"{path.name}: {action}")
    if stale:
        paths = "\n  ".join(str(path) for path in stale)
        raise ValueError(f"stale equipment assembly references:\n  {paths}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate stock equipment-function Capstone listings."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify previously generated local listings without rewriting them",
    )
    arguments = parser.parse_args()
    try:
        update(arguments.check)
    except (FileNotFoundError, OSError, RuntimeError, ValueError) as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
