"""Generate the English tables that replace NAME.BIN's retired kana data."""

import struct
from dataclasses import dataclass
from functools import cache
from pathlib import Path

from engine.script.context import DEFAULT_CONTEXT, EngineBuildContext
from engine.script.generated_asset import RuntimeUiContract
from engine.script.name.model import (
    MAX_NAME_LENGTH,
    NAME_FIELDS,
    load_atlas_metrics,
    load_font8_codes,
)
from engine.script.static_text import StaticTextAsset, load_static_asset

NAME_BASE = 0x06020000
DATA_START = 0x1E840
DATA_END = 0x202F8
ORIGINAL_DATA_SHA256 = (
    "0a696f1f14ed2e454c4d1e94ac23add7e788ff6b0709af8177ed58ecbfc6a7d2"
)

GRID_ROWS = 8
GRID_COLUMNS = 19
GRID_CONTENT_COLUMN = 3
GRID_CONTENT_WIDTH = 13
GRID_CONTENT_ROW = 1
END_CELL = 0x01F7
ENTRY_COLUMN = 11

TEXT_ASSET_PATH = Path("static") / "NAME.BIN.static.json"

TAB_KEYS = {"upper", "lower", "symbol"}
PROMPT_BLOCKS = {
    "first": "prompt_first",
    "last": "prompt_last",
    "codename": "prompt_codename",
    "city": "prompt_city",
    "ward": "prompt_ward",
}
OCCUPATION_BLOCKS = (
    "occupation_employee",
    "occupation_student",
    "occupation_official",
    "occupation_part_time",
    "occupation_business",
    "occupation_jobless",
)

FULLWIDTH_PUNCTUATION = {
    ".": 0x04,
    ",": 0x03,
    "'": 0x26,
    "-": 0x1D,
    "!": 0x09,
    "?": 0x08,
    "/": 0x1E,
    "&": 0x54,
    ":": 0x06,
    ";": 0x07,
    " ": 0x00,
}

AtlasMetrics = tuple[dict[str, int], dict[str, int]]


@dataclass(frozen=True)
class TabConfig:
    key: str
    rows: tuple[str, ...]


@dataclass(frozen=True)
class NameEntryConfig:
    tabs: tuple[TabConfig, ...]
    defaults: dict[str, str]


@dataclass(frozen=True)
class DataBlock:
    name: str
    offset: int
    data: bytes

    @property
    def address(self) -> int:
        return NAME_BASE + self.offset


@dataclass(frozen=True)
class NameDataLayout:
    blocks: tuple[DataBlock, ...]
    next_free: int
    label_addresses: dict[str, int]

    def block(self, name: str) -> DataBlock:
        try:
            return next(block for block in self.blocks if block.name == name)
        except StopIteration as error:
            raise KeyError(name) from error


@cache
def name_text_asset(
    context: EngineBuildContext = DEFAULT_CONTEXT,
) -> StaticTextAsset:
    return load_static_asset(
        TEXT_ASSET_PATH,
        Path("NAME.BIN"),
        context.text_generated_root,
        context.extracted_root,
    )


def atlas_codes(metrics: AtlasMetrics | None = None) -> dict[str, int]:
    return (load_atlas_metrics() if metrics is None else metrics)[0]


def atlas_advances(metrics: AtlasMetrics | None = None) -> dict[str, int]:
    return (load_atlas_metrics() if metrics is None else metrics)[1]


def asset_data(
    name: str,
    storage: str,
    asset: StaticTextAsset | None = None,
) -> bytes:
    asset = asset or name_text_asset()
    try:
        block = asset.blocks[name]
    except KeyError as error:
        raise ValueError(f"NAME.BIN static text is missing block {name!r}") from error
    if block.storage != storage:
        raise ValueError(
            f"NAME.BIN static-text block {name!r} must use {storage} storage"
        )
    return asset.data[block.offset : block.offset + block.size]


def asset_words(
    name: str,
    count: int | None = None,
    asset: StaticTextAsset | None = None,
) -> tuple[int, ...]:
    data = asset_data(name, "u16be", asset)
    words = struct.unpack(f">{len(data) // 2}H", data)
    if count is not None and len(words) != count:
        raise ValueError(f"NAME.BIN static-text block {name!r} must have {count} words")
    return words


def asset_ascii(
    name: str,
    metrics: AtlasMetrics | None = None,
    asset: StaticTextAsset | None = None,
) -> str:
    data = asset_data(name, "bytes", asset)
    if not data.endswith(b"\x00") or b"\x00" in data[:-1]:
        raise ValueError(f"NAME.BIN static-text block {name!r} is not one C string")
    text = data[:-1].decode("ascii")
    for character in text:
        if character not in atlas_codes(metrics):
            raise ValueError(
                f"NAME.BIN static-text block {name!r} uses an unmapped character"
            )
    return text


def asset_vwf_ascii(
    name: str,
    metrics: AtlasMetrics | None = None,
    asset: StaticTextAsset | None = None,
) -> str:
    """Recover ASCII from either generated byte strings or FONT16 cell rows."""
    asset = asset or name_text_asset()
    block = asset.blocks[name]
    if block.storage == "bytes":
        return asset_ascii(name, metrics, asset)
    if block.storage != "u16be":
        raise ValueError(
            f"NAME.BIN VWF text block {name!r} has unsupported "
            f"{block.storage!r} storage"
        )

    reverse_codes = {
        code: character
        for character, code in atlas_codes(metrics).items()
        if len(character) == 1 and 0x20 <= ord(character) < 0x7F
    }
    words = asset_words(name, asset=asset)
    terminator = next(
        (index for index, word in enumerate(words) if word in {0, 0x8000}),
        len(words),
    )
    if any(word not in {0, 0x8000} for word in words[terminator:]):
        raise ValueError(f"NAME.BIN VWF text block {name!r} has text after its padding")
    try:
        return "".join(reverse_codes[word] for word in words[:terminator])
    except KeyError as error:
        raise ValueError(
            f"NAME.BIN VWF text block {name!r} uses non-ASCII "
            f"FONT16 code {error.args[0]:#x}"
        ) from error


def fullwidth_code(character: str) -> int:
    if "A" <= character <= "Z":
        return 0xDC + ord(character) - ord("A")
    if "a" <= character <= "z":
        return 0xFC + ord(character) - ord("a")
    if "0" <= character <= "9":
        return 0xCB + ord(character) - ord("0")
    try:
        return FULLWIDTH_PUNCTUATION[character]
    except KeyError as error:
        raise ValueError(f"no KANJI.FON grid cell for {character!r}") from error


def charmap_byte(
    character: str,
    codes: dict[str, int] | None = None,
) -> int | None:
    return (load_font8_codes() if codes is None else codes).get(character)


def atlas_code(character: str, metrics: AtlasMetrics | None = None) -> int:
    codes = atlas_codes(metrics)
    return codes.get(character, codes["?"])


def atlas_advance(character: str, metrics: AtlasMetrics | None = None) -> int:
    advances = atlas_advances(metrics)
    return advances.get(character, advances["?"])


def validate_config(
    config: NameEntryConfig,
    metrics: AtlasMetrics | None = None,
) -> None:
    if len(config.tabs) != 3:
        raise ValueError("name entry requires exactly three tabs")
    if {tab.key for tab in config.tabs} != TAB_KEYS:
        raise ValueError("name-entry tab keys must be upper, lower, and symbol")
    for tab in config.tabs:
        for row in tab.rows:
            if len(row) > GRID_CONTENT_WIDTH:
                raise ValueError(
                    f"grid row exceeds {GRID_CONTENT_WIDTH} cells: {row!r}"
                )
            for character in row:
                fullwidth_code(character)
                if character not in atlas_codes(metrics):
                    raise ValueError(
                        f"grid character is absent from FONT16: {character!r}"
                    )

    if set(config.defaults) != {"city", "ward"}:
        raise ValueError("name defaults must define city and ward")
    for key, value in config.defaults.items():
        if len(value) > MAX_NAME_LENGTH:
            raise ValueError(f"default {key!r} exceeds {MAX_NAME_LENGTH} characters")
        for character in value:
            if character not in atlas_codes(metrics):
                raise ValueError(
                    f"default character is absent from FONT16: {character!r}"
                )


def load_config(
    contract: RuntimeUiContract,
    metrics: AtlasMetrics | None = None,
) -> NameEntryConfig:
    data = contract.section("name_entry")
    if not isinstance(data, dict):
        raise ValueError(f"{contract.path}: invalid name_entry section")
    config = NameEntryConfig(
        tabs=tuple(TabConfig(tab["key"], tuple(tab["rows"])) for tab in data["tabs"]),
        defaults=dict(data["defaults"]),
    )
    validate_config(config, metrics)
    return config


def build_grid(tab: TabConfig) -> tuple[bytes, bytes]:
    display = [[0] * GRID_COLUMNS for _ in range(GRID_ROWS)]
    commit = [[0] * GRID_COLUMNS for _ in range(GRID_ROWS)]
    for row_index, row in enumerate(tab.rows, GRID_CONTENT_ROW):
        for column_index, character in enumerate(row, GRID_CONTENT_COLUMN):
            display[row_index][column_index] = (
                0x11 if character == " " else fullwidth_code(character)
            )
            commit[row_index][column_index] = ord(character)
    display[4][15] = END_CELL
    return pack_grid(display), pack_grid(commit)


def pack_grid(rows: list[list[int]]) -> bytes:
    return b"".join(struct.pack(">19H", *row) for row in rows)


def text_width(text: str, metrics: AtlasMetrics | None = None) -> int:
    return sum(atlas_advance(character, metrics) for character in text)


def build_data_layout(
    config: NameEntryConfig,
    metrics: AtlasMetrics,
    font8_codes: dict[str, int],
    asset: StaticTextAsset | None = None,
) -> NameDataLayout:
    asset = asset or name_text_asset()
    blocks = []
    offset = DATA_START

    def add(name: str, data: bytes, *, align: int = 1) -> DataBlock:
        nonlocal offset
        offset = (offset + align - 1) & -align
        block = DataBlock(name, offset, data)
        blocks.append(block)
        offset += len(data)
        return block

    grid_blocks = []
    for index, tab in enumerate(config.tabs):
        display, commit = build_grid(tab)
        grid_blocks.append(
            (
                add(f"grid_{index}_display", display),
                add(f"grid_{index}_commit", commit),
            )
        )

    question = charmap_byte("?", font8_codes)
    if question is None:
        raise ValueError("FONT8 metrics must define a fallback question mark")
    charmap = bytes(font8_codes.get(chr(code), question) for code in range(0x20, 0x80))
    add("ascii_to_charmap", charmap)
    add(
        "ascii_to_atlas",
        struct.pack(
            ">96H",
            *(atlas_code(chr(code), metrics) for code in range(0x20, 0x80)),
        ),
    )
    add(
        "default_city_ward",
        config.defaults["city"].encode("ascii").ljust(MAX_NAME_LENGTH, b"\x00")
        + config.defaults["ward"].encode("ascii").ljust(MAX_NAME_LENGTH, b"\x00"),
    )
    add(
        "grid_bases",
        b"".join(
            struct.pack(">2I", display.address, commit.address)
            for display, commit in grid_blocks
        ),
        align=4,
    )
    add(
        "stage_pointers",
        struct.pack(">5I", *(spec.stage_address for spec in NAME_FIELDS)),
    )
    add(
        "ascii_to_width",
        bytes(atlas_advance(chr(code), metrics) for code in range(0x20, 0x80)),
    )

    prompt_names = tuple(PROMPT_BLOCKS[spec.key] for spec in NAME_FIELDS)
    strings = (
        *prompt_names,
        *OCCUPATION_BLOCKS,
        *(f"tab_{tab.key}" for tab in config.tabs),
        "label_occupation",
    )
    string_offsets = {}
    string_data = bytearray()
    for name in strings:
        string_offsets[name] = len(string_data)
        string_data.extend(
            asset_vwf_ascii(name, metrics, asset).encode("ascii") + b"\x00"
        )
    string_block = add("label_strings", bytes(string_data), align=4)
    add(
        "prompt_pointers",
        struct.pack(
            ">5I",
            *(string_block.address + string_offsets[name] for name in prompt_names),
        ),
        align=4,
    )

    occupation_centers = (88, 216, 88, 216, 88, 216)
    occupation_rows = (16, 16, 48, 48, 80, 80)
    add(
        "occupation_info",
        b"".join(
            struct.pack(
                ">IHH",
                string_block.address + string_offsets[name],
                max(0, center - text_width(label, metrics) // 2),
                row,
            )
            for name, center, row in zip(
                OCCUPATION_BLOCKS,
                occupation_centers,
                occupation_rows,
            )
            for label in (asset_ascii(name, metrics, asset),)
        ),
        align=4,
    )
    tab_centers = (48, 144, 240)
    add(
        "tab_info",
        b"".join(
            struct.pack(
                ">IHH",
                string_block.address + string_offsets[name],
                max(0, center - text_width(label, metrics) // 2),
                0,
            )
            for tab, center in zip(config.tabs, tab_centers)
            for name in (f"tab_{tab.key}",)
            for label in (asset_ascii(name, metrics, asset),)
        ),
    )

    if offset > DATA_END:
        raise ValueError(
            f"NAME.BIN generated data ends at {offset:#x}, beyond {DATA_END:#x}"
        )
    label_addresses = {
        name: string_block.address + string_offset
        for name, string_offset in string_offsets.items()
    }
    return NameDataLayout(tuple(blocks), offset, label_addresses)


def build_template(
    prompt_block: str,
    asset: StaticTextAsset | None = None,
) -> bytes:
    cells = [0] * 20
    cells[19] = 0x8000
    cells[:ENTRY_COLUMN] = asset_words(prompt_block, ENTRY_COLUMN, asset)
    return struct.pack(">20H", *cells)


def build_entry_template() -> bytes:
    cells = [0] * 20
    cells[19] = 0x8000
    return struct.pack(">20H", *cells)


def build_template_patches(
    asset: StaticTextAsset | None = None,
) -> dict[int, bytes]:
    asset = asset or name_text_asset()
    confirm = [0] * 20
    confirm[:ENTRY_COLUMN] = asset_words("prompt_confirm", ENTRY_COLUMN, asset)
    confirm[12:15] = asset_words("label_yes", 3, asset)
    confirm[16:18] = asset_words("label_no", 2, asset)
    return {
        0x20B78: build_entry_template(),
        0x20C18: struct.pack(">20H", *confirm),
        0x20CB8: build_template("prompt_occupation", asset),
    }
